- FE/package-lock.json
- FE/package.json
- FE/src/App.tsx
- FE/src/api/socket.ts
- FE/src/constants/socketEvents.ts
- FE/src/main.tsx
- FE/src/pages/GameSetupPage.tsx
- FE/src/pages/MainPage.tsx
- FE/tailwind.config.js
- #155 
- #156 
- #157 
<br/>
- 메인 페이지 구현
- 게임방 만들기 버튼 클릭 시 게임 생성 페이지로 이동 
- 게임 생성 페이지 구현
- 게임 옵션 설정(제목, 참가자 수, 게임 모드, 게임방 공개 여부)
- 방 만들기 버튼 클릭 시 서버에 socket으로 연결
<br/>
<br/>
- 잘못된 코드를 숨겨 놓았습니다. 찾아주세요
<br/>
> [FE] feat#155-157 메인 페이지 및 게임 생성 페이지 구현

- .github/workflows/deploy.yml
- BE/src/app.controller.spec.ts
- BE/src/app.service.ts
- #153 
<br/>
This pull request introduces a new deployment workflow for EC2 and modifies the greeting message in the backend service. The most important changes include the addition of a GitHub Actions workflow for deployment and updates to the greeting message in the backend service.
* [`.github/workflows/deploy.yml`](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R1-R100): Added a new GitHub Actions workflow to automate deployment to EC2. This includes steps for checking out the repository, setting up Node.js, installing dependencies, running tests, building the project, compressing files, and deploying to EC2.
* [`BE/src/app.service.ts`](diffhunk://#diff-bd08b5311390177abf2aaeddd0c540fb8eeef31edf3d981bbd05527d9b605667L6-R6): Changed the greeting …
> [BE] feat#156 자동배포 구현

- .gitignore
- BE/package-lock.json
- BE/package.json
- BE/src/app.module.ts
- #177 
<br/>
- @nestjs/typeorm, typeorm, mysql2 모듈 설치
- TypeOrm 모듈 설정
<br/>
<br/>
> [BE] feat#177 MySQL, TypeORM 관련 설치 및 설정

- BE/package-lock.json
- BE/src/game/game.gateway.ts
- #140 
- #25 
<br/>
- 플레이어 퇴장 시, 같은 게임방에 남아있는 플레이어들에게 exitRoom 전송
- 호스트 퇴장 시, 게임방의 플레이어들 중 첫 번째 플레이어에게 호스트 넘겨주기
<br/>
<br/>
> [BE] feat#140,#25 exitRoom 전송, host 퇴장 시 변경

- FE/src/App.tsx
- FE/src/components/GameHeader.tsx
- FE/src/components/QuizSettingModal.tsx
- FE/src/components/QuizView.tsx
- FE/src/pages/MainPage.tsx
- FE/src/pages/QuizSetupPage.tsx
- #59 
- #44 
- #45 
- #46 
<br/>
- 퀴즈 생성 페이지 레이아웃 개발
- 퀴즈 조회 및 설정 모달 레이아웃 개발
<br/>
<br/>
<br/>
> [FE] feat#59#44-46 퀴즈 생성 및 조회 레이아웃 개발

- FE/src/api/mocks/SocketMock.ts
- FE/src/api/mocks/socketMocks/SocketMockChat.ts
- FE/src/api/mocks/socketMocks/SocketMockStartGame.ts
- FE/src/api/mocks/socketMocks/index.ts
- FE/src/api/socket.ts
- FE/src/api/socketEventTypes.ts
- FE/src/components/Player.tsx
- FE/src/components/QuizHeader.tsx
- FE/src/components/QuizOptionBoard.tsx
- FE/src/constants/quizState.ts
- FE/src/pages/GamePage.tsx
- FE/src/store/usePlayerStore.ts
- FE/src/store/useQuizStore.ts
- #198
<br/>
- 채팅 모킹
- 게임 시작 모킹
- 퀴즈와 선택지 받아오기 모킹
- 정답 공개 모킹
- 스코어 계산, 정답 맞춘 유저 캐릭터 이펙트 효과 모킹
<br/>
<br/>
- 모킹 열심히 했습니다.
<br/>
> [FE] feat#198 프론트 mocking 설정 후 게임 진행 테스트

- BE/src/InitDB/InitDB.Service.ts
- BE/src/app.module.ts
- BE/src/auth/auth.controller.ts
- BE/src/auth/auth.module.ts
- BE/src/auth/decorators/current-user.decorator.ts
- BE/src/auth/guard/jwt.strategy.ts
- BE/src/auth/guard/ws-jwt-auth.guard.ts
- BE/src/game/game.gateway.ts
- BE/src/game/game.module.ts
- BE/src/quiz-set/entities/quiz-set.entity.ts
- BE/src/quiz-set/quiz-set.controller.ts
- BE/src/quiz-set/quiz-set.module.ts
- BE/src/quiz-set/service/quiz-set-create.service.ts
- BE/src/quiz-set/service/quiz-set-delete.service.ts
- BE/src/quiz-set/service/quiz-set-update.service.ts
- BE/src/quiz-set/service/quiz-set.service.ts
- BE/test/integration/game.integration.spec.ts
- BE/test/integration/quiz.integration.spec.ts
- #227 
- #228 
<br/>
- 퀴즈셋 기능에 유저 확인 추가
- 게임 join에 유저 확인 추가
<br/>
<br/>
> [BE] feat#227#228 퀴즈셋 기능에 유저 확인 추가, 게임 join 에 유저 확인 추가

- BE/src/common/constants/redis-key.constant.ts
- BE/src/game/redis/subscribers/scoring.subscriber.ts
- BE/src/game/service/game.service.ts
- #239
<br/>
- 노션 일지: https://www.notion.so/s0n9/fix-3716a919cc2548e2aa763425af2feef8?pvs=4
<br/>
정상적으로 게임 진행 완료된 모습 
<br/>
<br/>
> [BE] fix#239 멀티프로세스로 실행시 endQuizTime이 발생 안 되는 이슈 해결

- BE/test/integration/game.integration.spec.ts
- BE/test/integration/quiz.integration.spec.ts
- #238 
<br/>
- 테스트 코드 오류 수정
<br/>
<br/>
> [BE] test#238 테스트 코드 오류 수정

- FE/src/pages/GamePage.tsx
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [FE] fix errormodal 삭제

- BE/src/common/decorators/parse-int-or-default.decorator.ts
- BE/src/waiting-room/waiting-room.controller.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [BE] fix: 빈 문자열 쿼리로 들어왔을 때 기본값으로 바뀌도록 수정

- BE/src/quiz-set/quiz-set.controller.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [BE] fix: quizset 단일 조회 transform, api endpoint 수정

- .github/workflows/deploy.yml
- BE/src/common/decorators/parse-int-or-default.decorator.ts
- BE/src/waiting-room/waiting-room.controller.ts
- FE/src/api/rest/authApi.ts
- FE/src/api/rest/instance.ts
- FE/src/api/rest/quizTypes.ts
- FE/src/api/socket/socket.ts
- FE/src/api/socket/socketEventTypes.ts
- FE/src/components/ErrorModal.tsx
- FE/src/components/GameHeader.tsx
- FE/src/components/LobbyList.tsx
- FE/src/components/QuizOptionBoard.tsx
- FE/src/components/QuizSettingModal.tsx
- FE/src/pages/GameLobbyPage.tsx
- FE/src/pages/GamePage.tsx
- FE/src/pages/GameSetupPage.tsx
- FE/src/pages/LoginPage.tsx
- FE/src/pages/MainPage.tsx
- FE/src/pages/QuizSetupPage.tsx
- FE/src/store/useChatStore.ts
- FE/src/store/usePlayerStore.ts
- FE/src/store/useQuizStore.ts
- FE/src/store/useRoomStore.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [FE] Hotfix

- BE/src/quiz-set/quiz-set.controller.ts
- #이슈번호
<br/>
- 실수 죄송합니드앗...!
<br/>
<br/>
<br/>
> [BE] fix: quizSetController 로그 찍으면서 잘못 수정했던 부분 고침

- FE/src/api/socket/mocks/SocketMock.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockChat.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockLoadTest.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockLoadTestOnlyMove.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockLoadTestWithQuiz.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockNextQuiz.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockStartEnd.ts
- FE/src/api/socket/mocks/socketMocks/SocketMockStartGame.ts
- FE/src/api/socket/mocks/socketMocks/index.ts
- FE/src/features/game/components/AnswerModal.tsx
- FE/src/features/game/components/Chat.tsx
- FE/src/features/game/components/Modal.tsx
- FE/src/features/game/components/ParticipantDisplay.tsx
- FE/src/features/game/components/Player.tsx
- FE/src/features/game/components/QuizHeader.tsx
- FE/src/features/game/components/QuizOptionBoard.tsx
- FE/src/features/game/components/QuizSetSearchList.tsx
- FE/src/features/game/components/QuizSettingModal.tsx
- FE/src/features/game/components/ResultModal.tsx
- FE/src/features/game/data/socketListener.ts
- FE/src/features/game/data/store/usePlayerStore.ts
- FE/src/features/game/pages/GamePage.tsx
(확인 후 지워주세요)
- #이슈번호
<br/>
- 플레이어 스토어 최적화
- 전체 플레이어 정보를 담는 player를 배열에서 Map으로 변경
- 플레이어가 이동할 때 이동한 플레이어만 리렌더링
- 자잘한 수정
- 닉네임 입력 모달에 취소 버튼 제거
- 정답 모달에 닫기 버튼 제거
- 자잘한 최적화
- 카운트 다운 프로그레스바 transform으로 길이 변경
<br/>
<br/>
<br/>
> [FE] 플레이어 스토어 최적화

- BE/src/common/constants/socket-events.ts
> [BE] fix# GET_SELF_ID 이벤트 이름 수정

- BE/src/common/constants/socket-events.ts
- BE/src/game/redis/subscribers/room.subscriber.ts
- BE/src/game/redis/subscribers/timer.subscriber.ts
- BE/src/game/service/game.room.service.ts
> [BE] fix# 새 호스트 설정 및 이벤트 전송 추가

- BE/src/game/game.gateway.ts
> [BE] fix: CORS Origin 설정 및 쿠키 SameSite, Secure 옵션 추가

- FE/index.html
- FE/src/api/socket/hooks/useSocketException.ts
- FE/src/api/socket/socketEventTypes.ts
- FE/src/features/auth/LoginModal.tsx
- FE/src/features/game/components/ParticipantDisplay.tsx
- FE/src/features/game/data/socketListener.ts
- FE/src/features/game/pages/GamePage.tsx
- FE/src/features/game/pages/GameSetupPage.tsx
- FE/src/features/game/pages/PinPage.tsx
- FE/src/pages/MainPage.tsx
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [FE] 최신 수정 사항 반영

- BE/src/game/redis/game-redis-memory.service.ts
- BE/src/game/redis/subscribers/timer.subscriber.ts
- BE/src/game/service/game.room.service.ts
> [BE] fix# 채점 오류 해결 및 TTL 관리 삭제

- BE/src/game/redis/subscribers/player.subscriber.ts
- BE/src/game/service/game.service.ts
- BE/src/game/validations/game.validator.ts
- #이슈번호
<br/>
이 풀 리퀘스트는 게임 서비스에서 플레이어 위치 업데이트 프로세스를 최적화하고 코드 효율성을 개선하는 데 중점을 둡니다. 주요 변경사항으로는 새로운 검증 방법 도입, 일괄 작업을 위한 Redis 파이프라인 사용, 그리고 updatePosition 메서드에 대한 문서화 개선이 포함됩니다.
- 최적화 및 개선사항:
[BE/src/game/redis/subscribers/player.subscriber.ts]: 성능 향상을 위해 개별 Redis 쿼리를 단일 일괄 작업으로 모든 플레이어 상태를 가져오는 파이프라인으로 대체했습니다.
[BE/src/game/service/game.service.ts]: updatePosition 메서드를 단일 작업으로 여러 키를 설정하는 Redis 파이프라인을 사용하도록 업데이트하고, 코드 문서화를 위한 포괄적인 JSDoc 주석을 추가했습니다.
[BE/src/game/validations/game.validator.ts]: 게임 ID를 직접 비교하여 검증 프로세스를 간소화하는 새로운 validatePlayerInRoomV2 메서드를 추가했습니다.
<br/>
- 개선전
- 개선후
<br/>
<br/>
> [BE] fix: updatePosition 성능개선

- BE/src/game/redis/subscribers/timer.subscriber.ts
- BE/src/game/service/game.room.service.ts
- 1등 호스트 오류 수정
- 게임 시작 시 옵션 전송
- 게임이 시작되어 있는 경우 게임 시작 메시지 전송
<br/>
> [BE] fix# 순위 오류, 옵션 오류, 재접속 오류 수정

- BE/src/game/redis/subscribers/player.subscriber.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [BE] fix: 타입 문제 해결

- BE/src/game/game.gateway.ts
- BE/src/game/redis/subscribers/timer.subscriber.ts
> [BE] fix# 게임 종료 후 새로운 호스트 아이디 오류 수정

- README.md
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [공통] docs: 기술 스택 추가

- README.md
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [공통] docs: gif 추가

- BE/src/game/redis/subscribers/timer.subscriber.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [BE] fix: 싱글 플레이 시 퀴즈 바로 끝나는 문제 해결

- README.md
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [공통] 리드미 입체 버튼

- FE/src/features/auth/LoginModal.tsx
- FE/src/features/game/pages/PinPage.tsx
- FE/src/features/quiz/QuizSetupPage.tsx
- FE/src/pages/MainPage.tsx
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [FE] 비회원 로그인 및 디자인 수정

- BE/src/game/redis/subscribers/player.subscriber.ts
(확인 후 지워주세요)
- #이슈번호
<br/>
<br/>
<br/>
<br/>
> [BE] fix: position 키 변경일 때만 배치처리

- README.md
- 배치 처리로 최적화한 부분 추가했습니다!
- 노션 링크, 위키 링크도 수정했습니다!
- 위키는 아직 옮기는 중입니다! 노션에서 다 쓰고 나서 한번에 옮길 예정입니다.
> [공통] 리드미 백엔드 위치 업데이트 최적화 수정 (배치처리 추가)
