FE/package.json, FE/src/App.tsx, FE/src/api/socket.ts, FE/src/api/socketEventTypes.ts, FE/src/components/Chat.tsx, FE/src/components/GameHeader.tsx, FE/src/components/ParticipantDisplay.tsx, FE/src/components/Player.tsx, FE/src/components/QuizOptionBoard.tsx, FE/src/pages/GamePage.tsx, FE/src/pages/GameSetupPage.tsx, FE/src/store/useChatStore.ts, FE/src/store/usePlayerStore.ts, FE/src/store/useRoomStore.ts
- #16 
- #20 
<br/>
- 서버와 연동하여 채팅 송수신 가능하도록 구현
- 서버와 연동하여 게임 대기방에서 참가자 목록 보이도록 구현
- 방 설정 및 생성 페이지에서 방 생성 시 게임 페이지로 이동하도록 구현
- 플레이어 보드에 띄움(일단 이모티콘으로)
<br/>
<br/>
<br/>
=> [FE] feat#16#20

BE/package-lock.json, BE/package.json, BE/src/app.module.ts, BE/src/quiz/dto/create-quiz.dto.ts, BE/src/quiz/dto/update-quiz.dto.ts, BE/src/quiz/quiz.controller.ts, BE/src/quiz/quiz.service.spec.ts, BE/src/quiz/quiz.service.ts, BE/test/quiz.e2e-spec.ts
- #47 
- #179
<br/>
- 개발일지 : https://www.notion.so/s0n9/897a4c8490904f7588b0330f0ea6d73a?p=66de19cbe45d430ab143538c63ed1ec4&pm=s#b072b8bf4e3c422ea657febe6a2ffaee
- 퀴즈셋 c u d 구현
- e2e test code 작성
<br/>
<br/>
- e2e test같이 db에 의존적인 test가 자동배포의 test에서 돌아갈런지 알아봐야함.
<br/>
=> [BE] feat#47#179 퀴즈셋 cud 구현, test code 작성

FE/package-lock.json, FE/package.json, FE/public/mockServiceWorker.js, FE/src/api/mocks/SocketMock.ts, FE/src/api/mocks/socketMocks/SocketMockStartGame.ts, FE/src/api/socketEventTypes.ts, FE/src/components/QuizHeader.tsx, FE/src/components/QuizOptionBoard.tsx, FE/src/components/QuizPreview.tsx, FE/src/components/QuizSetSearchList.tsx, FE/src/components/QuizSettingModal.tsx, FE/src/hooks/useServerDate.ts, FE/src/main.tsx, FE/src/mocks/browser.ts, FE/src/mocks/data.ts, FE/src/mocks/handlers.ts
- #46 
<br/>
- 선택한 퀴즈셋 서버로 전송
- 퀴즈셋 검색 및 무한 스크롤 구현
- 클라이언트와 서버 시간 동기화
<br/>
클라이언트 서버 시간 동기화
<br/>
<br/>
=> [FE] feat#46 선택한 퀴즈셋 서버로 전송

FE/src/App.tsx, FE/src/components/Chat.tsx, FE/src/pages/LoginPage.tsx, FE/src/pages/MainPage.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/QuizSetupPage.tsx
- #76 
- #84 
- #224 
<br/>
- 로그인/회원가입 UI
- 마이페이지 UI
- 채팅 스크롤 개선
<br/>
- ### 마이페이지, 로그인/회원가입 화면
<div>
</div>
- ### 채팅 스크롤 개선
<br/>
- 마이페이지에 들어갈 내용에 대해서는 추가 논의 ex) 포인트
<br/>
=> [FE] feat#76#84#224 로그인/회원가입, 마이페이지 ui, 채팅 스크롤 개선

BE/src/quiz-set/dto/quiz-set-list-response.dto.ts, BE/src/quiz-set/quiz-set.controller.ts, BE/src/quiz-set/service/quiz-set-read.service.ts, BE/src/quiz-set/service/quiz-set.service.ts, BE/src/waiting-room/dto/waiting-room-list.response.dto.ts, BE/src/waiting-room/waiting-room.controller.ts, BE/src/waiting-room/waiting-room.service.spec.ts, BE/src/waiting-room/waiting-room.service.ts, BE/test/integration/quiz.integration.spec.ts
- #230
<br/>
- 아직 성능(시간 복잡도)가 좋지는 않습니다. 
- best practice 알아보면서 하려다가, 이렇게 하면 오늘 안에 하기 힘들 것 같아서 우선은 명세에 따라 응답줄 수 있게 구현해뒀습니다. 
- 정해진 기간 내에 구현하는 것도 중요하다는 말이 머릿속에 스쳐지나가서요!
- 향후 성능 최적화의 대상 중의 하나가 될 수도 있을 것 같습니다. 
<br/>
<br/>
- 감사합니다! 
<br/>
=> [BE] feat#230 퀴즈셋 목록 조회, 대기방 목록 조회 API 커서 기반 페이징 구현

FE/src/api/socket.ts
- socket 연결 요청은 NginX를 통해 3333으로 받고, 3000번대 포트 was로 보내주는 방식으로 구현되어 있습니다!
- 이에 따라 FE 연결 요청 부분도 수정해서 올렸습니다!
<br/>
<br/>
<br/>
=> [FE] socket.io 연결하는 URL port 수정 (기본값 3000 -> 3333)

.github/workflows/deploy.yml, BE/src/game/interceptor/gameActivity.interceptor.ts, BE/test/integration/game.integration.spec.ts
- #241  
<br/>
* 자동배포 수정
dist/src내의 main.js를 실행하도록 변경
안되던게 그냥 env파일 ip를 잘못적어줘서인가? 그런듯
현재 config경로
여기있는 env를 잘찾는다.
<br/>
<br/>
<br/>
=> [BE] feat#241 자동배포 수정

FE/src/api/socket/socket.ts, FE/src/api/socket/socketEventTypes.ts, FE/src/constants/socketEvents.ts, FE/src/features/game/components/Chat.tsx, FE/src/features/game/components/GameHeader.tsx, FE/src/features/game/components/ParticipantDisplay.tsx, FE/src/features/game/data/socketListener.ts
- #30
<br/>
- 강퇴 기능 구현
- 최적화
- 리액트 dev tool을 통해 채팅 리렌더링시에 GameHeader도 같이 리렌더링되는 상황파악
- React.memo를 활용하여 값이 변하지 않았을 경우 리렌더링 되지 않도록 수정
<br/>
- ### 개선 전
- ### 개선 후
<br/>
- 없음
<br/>
=> [FE] feat#30 강퇴 기능 구현 및 채팅렌더링 최적화

BE/.eslintrc.js, BE/package-lock.json, BE/package.json, BE/src/common/constants/exception-message.ts, BE/src/common/constants/socket-events.ts, BE/src/game/dto/kick-room.dto.ts, BE/src/game/game.gateway.ts, BE/src/game/redis/subscribers/player.subscriber.ts, BE/src/game/service/game.room.service.ts, BE/src/game/validations/game.validator.ts, BE/src/main.ts
- #263 
<br/>
- https://www.notion.so/s0n9/897a4c8490904f7588b0330f0ea6d73a?p=5a1e14f717e84d5a9957a261b5550eb6&pm=s
- 강퇴기능 구현, 재입장 불가는 todo
- 핀포인트 도입 
- socket io 미지원
- nestjs지원 && socket io 를 모니터링 하는 도구를 찾거나 직접 (로거 수준으로) 구현해야할듯
- 세세한 api 분석 측면에서는 엄청 강력한 툴 맞음.
- cpu, mem, db conn등 큰그림을 보려면 프로메테우스 도입필요 할듯.
<br/>
<br/>
- 소켓도 지원되게 도전?
- 원래는 모니터링용 서버를 하나 더 띄우는게 정석, 일단 was 서버에 넣어놓음.
<br/>
=> [BE] feat#263 강퇴구현, 모니터링 도입

BE/src/common/interceptor/SocketEventLoggerInterceptor.ts, BE/src/game/game.gateway.ts, BE/src/game/service/game.chat.service.ts, BE/src/game/service/game.room.service.ts, BE/src/game/service/game.service.ts, BE/src/game/service/quiz.cache.service.ts
- #229 
<br/>
이 풀 리퀘스트는 백엔드 애플리케이션의 WebSocket 이벤트와 서비스 메서드에 대한 포괄적인 로깅 및 추적 기능을 도입합니다. 변경 사항에는 소켓 이벤트를 로깅하기 위한 새로운 인터셉터와 메서드 호출 및 실행 시간을 추적하기 위한 데코레이터 구현이 포함됩니다.
주요 변경 사항:
* `BE/src/common/interceptor/SocketEventLoggerInterceptor.ts`: WebSocket 이벤트와 서비스 메서드 호출을 로깅하기 위한 `SocketEventLoggerInterceptor` 추가. `AsyncLocalStorage`를 사용하여 추적 컨텍스트를 관리하는 `TraceStore`와 `TraceContext` 클래스 도입. 서비스 메서드와 클래스를 추적하기 위한 `Trace`와 `TraceClass` 데코레이터 구현.
* `BE/src/game/game.gateway.ts`: 소켓 이벤트를 로깅하기 위해 WebSocket 게이트웨이에 `SocketEventLoggerInterceptor` 통합. 테스트 목적으로 느린 이벤트를 시뮬레이션하고 로깅하기 위한 새로운 `handleSlowEvent` 메서드 추가.
* `BE/src/game/service/game.chat.service.ts`: 모든 메서드의 추적을 활성화하기 위해 `GameChatService` 클래스에 `TraceClass` 데코레이터 적용.
* `BE/src/game/service/game.room.service.ts`: 메서드 추적을 위해 `GameRoomService` 클래스에 …
=> [BE] feat#229 모니터링 인터셉터 구현

FE/src/api/socket/mocks/SocketMock.ts, FE/src/api/socket/socket.ts, FE/src/api/socket/socketEventTypes.ts, FE/src/features/game/components/AnswerModal.tsx, FE/src/features/game/components/GameHeader.tsx, FE/src/features/game/components/NicknameModal.tsx, FE/src/features/game/components/ParticipantDisplay.tsx, FE/src/features/game/components/Player.tsx, FE/src/features/game/components/QuizHeader.tsx, FE/src/features/game/components/QuizSetSearchList.tsx, FE/src/features/game/components/QuizSettingModal.tsx, FE/src/features/game/components/ResultModal.tsx, FE/src/features/game/data/socketListener.ts, FE/src/features/game/data/store/usePlayerStore.ts, FE/src/features/game/pages/GamePage.tsx, FE/src/features/game/pages/GameSetupPage.tsx, FE/src/features/game/pages/PinPage.tsx, FE/src/features/game/utils/emoji.ts, FE/src/index.css, FE/tailwind.config.js
(확인 후 지워주세요)
- #이슈번호
<br/>
- API 명세에 변경에 따라 몇 가지 수정
- 퀴즈 설정 모달에 검색어 없어도 퀴즈 리스트뜨도록 구현
- 다양한 이모티콘
- 죽으면 유령으로 바뀌고 하늘로 승천함
한번 봐주세용
<https://news.taskify.shop/game/test-load-with-quiz>
<br/>
<br/>
<br/>
=> [FE] feat 디자인

BE/src/common/constants/exception-message.ts, BE/src/game/game.gateway.ts
- #275 
- #276 
<br/>
이 Pull Request는 WebSocket 연결 프로세스의 에러 처리와 로깅을 개선하고, 약간의 코드 정리를 포함합니다. 가장 중요한 변경사항은 새로운 예외 메시지 추가, 사용자 친화적인 로깅 메시지 업데이트, 클라이언트 연결 중 에러 처리 강화입니다.
- 에러 처리 및 로깅 개선:
BE/src/common/constants/exception-message.ts: 소켓 연결 실패 시 더 자세한 정보를 제공하기 위해 새로운 예외 메시지 CONNECTION_ERROR를 추가했습니다.
BE/src/game/game.gateway.ts: handleConnection 메소드에 try-catch 블록을 추가하여 에러 처리를 개선했습니다. 이제 이 메소드는 에러를 로깅하고, 클라이언트에 에러 메시지를 전송하며, 실패 시 클라이언트 연결을 끊습니다.
- 코드 정리:
BE/src/game/game.gateway.ts: 코드베이스 정리를 위해 Server와 UseGuards와 같은 사용하지 않는 임포트를 제거했습니다.
BE/src/game/game.gateway.ts: 로그 메시지를 더 사용자 친화적으로 업데이트했습니다.
- 클래스 레벨에 Exception Filter가 작동하지 않았던 이유
원인 : engine.io(socket.io의 로우레벨)에서 connect event가 일어나기 때문에, 이시점에는 nestjs의 미들웨어가 로드되지 않은 시점이다! 따라서 우리가 만든 ExceptionFilter가 없는 시점에 생긴 error 이기 때문에 잡히지 않는것!
<br/> …
=> [BE] fix#275#276 소켓연결할때 error 발생시 서버가 죽는버그

BE/src/quiz-set/entities/quiz-set.entity.ts, BE/src/quiz-set/quiz-set.controller.ts, BE/src/quiz-set/service/quiz-set-create.service.ts
- #281 
<br/>
- 카테고리 enum 설정
- 클라에게 구체적인 에러 메세지 전송
<br/>
<br/>
<br/>
=> [BE] feat#281 카테고리 enum 설정

BE/src/game/redis/game-redis-memory.service.ts, BE/src/game/redis/subscribers/room.cleanup.subscriber.ts, BE/src/game/service/game.room.service.ts
이 Pull Request는 Redis 기반 게임 서비스에서 비활성 방 처리와 정리 프로세스를 개선하기 위한 여러 업데이트를 포함합니다. 가장 중요한 변경사항은 비활성 방 확인을 위한 새로운 메소드 추가, 방 정리 프로세스 수정, 그리고 중복 코드 제거입니다.
- 비활성 방 처리 개선:
BE/src/game/redis/game-redis-memory.service.ts: cron 작업을 사용하여 주기적으로 비활성 방을 확인하고 정리하는 새로운 메소드 checkInactiveRooms를 추가했습니다. 이 메소드는 Redis SCAN을 사용하여 대규모 방 세트를 안전하게 처리하고 배치 단위로 처리합니다.
- 방 정리 프로세스 강화:
BE/src/game/redis/subscribers/room.cleanup.subscriber.ts: 방 정리 프로세스를 업데이트하여 방 데이터 자체뿐만 아니라 해당 방의 플레이어 목록을 가져와서 그들의 데이터도 삭제하도록 수정했습니다.
- 코드 정리 및 리팩토링:
BE/src/game/service/game.room.service.ts: GameRedisMemoryService의 새로운 구현으로 대체되었기 때문에 기존의 checkInactiveRooms 메소드와 관련 cron 작업을 제거했습니다.
- 사소한 변경사항:
BE/src/game/redis/game-redis-memory.service.ts: 일관된 구조를 따르도록 imports 순서를 재정렬했습니다.
BE/src/game/service/game.room.service.ts: 사용하지 않는 import 구문을 …
=> [BE] fix-room-clean

BE/src/common/constants/game.ts, BE/src/game/dto/create-game.dto.ts, BE/src/game/dto/update-room-option.dto.ts, BE/src/game/redis/subscribers/player.subscriber.ts, BE/src/game/redis/subscribers/timer.subscriber.ts, BE/src/game/service/game.chat.service.ts, BE/src/game/service/game.room.service.ts, BE/src/user/entities/user-quiz-archive.entity.ts
- #이슈번호
<br/>
- 서바이벌 모드 끝난 이후 이동 안 되는 이슈 해결
- 해결법: 게임 끝날 때 isAlive 모두 1로 처리
- 다 죽거나 1등만 남았을 때 게임 끝나게 처리
- 해결법: Promise 관련 이슈 해결 
- 죽은자끼리 채팅 안 되는 현상 해결
- 원인: playerId로 채팅을 하나하나 보내주는데, playerId가 socketId가 아니여서 발생
- 해결법: redis에 player정보 넣을 때 socketId도 추가 
- '1', '0' 상수화
```tsx
// 생존 모드에서 모두 탈락하진 않았는지 체크
const players = await this.redis.smembers(REDIS_KEY.ROOM_PLAYERS(gameId));
const alivePlayers = players.filter(async (id) => {
const isAlive = await this.redis.hget(REDIS_KEY.PLAYER(id), 'isAlive');
return isAlive === '1';
});
// 게임 끝을 알림
if (quizList.length <= newQuizNum || alivePlayers.length === 0) {
```
- filter는 Promise 처리하지 못한다고 함
- 그래서 alivePlayers는 그대로 Promise 배열이 되어버림. 즉, 배열의 길이가 0일 수가 없음 
- map, filter, forEach 등은 비동기 처리를 기다리지 않음
- 그래서 아래처럼 Promise.all을 활용하거나, for문을 써야 함
```tsx …
```
=> [BE] fix: 서바이벌 모드 디버깅

FE/src/features/lobby/GameLobbyPage.tsx, FE/src/features/lobby/LobbyList.tsx
=> [FE] fix: 대기방 새로고침 기능 수정

BE/src/InitDB/InitDB.controller.ts, BE/test/integration/quiz-set/quiz.integration.spec.ts
이 Pull Request는 `InitDB.controller.ts`와 `quiz.integration.spec.ts` 파일의 변경사항을 포함합니다. 
가장 중요한 변경사항은 `InitDBController`를 수정하여 `create` 메서드를 호출하는 대신 `HttpException`을 throw하도록 변경한 것과, 다양한 테스트 케이스에서 `category` 필드를 'IT'로 변경한 것입니다.
`InitDB.controller.ts` 변경사항:
* `InitDBController`의 `create` 메서드를 수정하여 'test용 api 입니다.'라는 메시지와 HTTP 상태 코드 501을 가진 `HttpException`을 throw하도록 변경했습니다.
`quiz.integration.spec.ts`의 테스트 케이스 업데이트:
* category에 있는 제약조건을 지키기 위해 여러 테스트 케이스에서 `category` 필드를 'PROGRAMMING' 또는 'TEST'에서 'IT'로 변경했습니다.
이러한 변경은 테스트용 API의 접근을 제한하고, 테스트 케이스의 카테고리를 일관되게 만드는 것이 목적입니다.
<br/>
<br/>
<br/>
=> [BE] hotfix#테스트용 api 삭제, fix db test

BE/src/InitDB/InitDB.controller.ts, BE/src/InitDB/QUIZ_SET_TEST_DATA.ts, BE/src/main.ts, BE/src/quiz-set/entities/quiz-choice.entity.ts, BE/src/quiz-set/entities/quiz-set.entity.ts, BE/src/quiz-set/entities/quiz.entity.ts, BE/src/quiz-set/quiz-set.controller.ts, BE/src/quiz-set/service/quiz-set-read.service.ts, docs/db.MD
- #329
<br/>
- 문서 : https://github.com/boostcampwm-2024/web10-QuizGround/wiki/Full-Text-Search%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%ED%80%B4%EC%A6%88%EA%B2%80%EC%83%89-50%25-%EC%84%B1%EB%8A%A5%EA%B0%9C%EC%84%A0
이 PR은 백엔드 서비스의 여러 변경사항을 포함하며, 데이터베이스 초기화, 퀴즈셋 데이터 관리, 검색 기능 개선에 중점을 두었습니다. 가장 중요한 변경사항은 다음과 같습니다:
* initDB api가 카테고리 제한때문에 오류를 뱉는 문제.
* `QUIZ_SET_TEST_DATA.ts`: "영어 문법 테스트" 퀴즈셋의 카테고리를 'ENGLISH'에서 'LANGUAGE'로 변경했습니다.
* `quiz-choice.entity.ts`: `choiceContent` 컬럼에 `ngram` 파서를 사용하는 전문 검색 인덱스를 추가했습니다.
* `quiz-set.entity.ts`: `title` 컬럼에 `ngram` 파서를 사용하는 전문 검색 인덱스를 추가했습니다.
* `quiz.entity.ts`: `quiz` 컬럼에 `ngram` 파서를 사용하는 전문 검색 인덱스를 추가했습니다.
* `quiz-set.controller.ts`: 퀴즈셋 목록을 가져오는데 걸리는 시간을 측정하기 위한 성능 로깅을 추가했습니다.
* `quiz-set-read.service.ts`: `findSearchTargetIds` 메서드를 전문 검색을 위한 …
=> [BE] feat#329 퀴즈검색 성능개선

BE/src/game/redis/subscribers/player.subscriber.ts, BE/src/game/service/BatchProcessor.ts, BE/src/game/service/game.chat.service.ts
- #333 
<br/>
이 PR은 게임 이벤트를 더 효율적으로 처리하기 위한 새로운 배치 처리 시스템을 도입합니다. 변경사항에는 배치 프로세서의 생성과 이를 플레이어 위치 업데이트 및 채팅 메시지 처리에 통합하는 내용이 포함되어 있습니다.
좀 더 자세히 설명하면:
배치 처리 시스템 도입으로 실시간 이벤트 처리의 효율성 향상
플레이어 위치 업데이트와 채팅 메시지를 배치로 처리하도록 개선
서버 부하 감소 및 성능 최적화 달성
이것은 게임의 실시간 처리 성능을 향상시키기 위한 주요 개선사항입니다.
변경사항을 크게 3부분으로 나누어 설명드리겠습니다:
1. **BatchProcessor 생성**
- `BE/src/game/service/BatchProcessor.ts` 파일에 새로운 `createBatchProcessor` 함수를 추가했습니다.
- 이 함수는 다양한 게임 이벤트에 대한 배치 처리기를 생성하고 관리합니다.
- 데이터 추가(pushData), 배치 처리(processBatch), 자동 처리 시작(startProcessing), 데이터 초기화(clear) 등의 메서드를 포함합니다.
2. **플레이어 위치 업데이트 통합**
- `BE/src/game/redis/subscribers/player.subscriber.ts` 파일에서 기존의 위치 업데이트 처리 방식을 새로운 배치 처리기로 교체했습니다.
- 위치 업데이트를 위한 배치 처리기를 생성하고, 100ms 간격으로 처리를 시작하도록 설정했습니다.
- 위치 데이터를 배치 처리기에 push하는 방식으로 변경되었습니다.
3. **채팅 메시지 통합**
- …
=> [BE] feat#333 배치기능 모듈화

FE/package-lock.json, FE/package.json, FE/src/api/socket/socketEventTypes.ts, FE/src/components/QuizPreview.tsx, FE/src/features/game/components/AnswerModal.tsx, FE/src/features/game/components/Chat.tsx, FE/src/features/game/components/ParticipantDisplay.tsx, FE/src/features/game/components/QuizHeader.tsx, FE/src/features/game/components/QuizOptionBoard.tsx, FE/src/features/game/components/QuizSetSearchList.tsx, FE/src/features/game/data/socketListener.ts, FE/src/index.css
- updatePosition 및 chatMessage 이벤트 소켓 배치 적용
- 하위 호환성을 위해 배치로 보내지 않아도 돌아가게 했습니다
- 일부 디자인 변경
- 정답 모달에서 정답 여부만 보여줌
- 선택지가 길어질 때 박스를 넘어가지 않도록 수정
- 퀴즈 프리뷰 줄바꿈 3까지 가능 그 뒤에는 ...으로 표시
- 채팅 "~환영합니다" 변경
- 폰트 변경(일부 글자가 보이지 않는 이슈로)
<br/>
<br/>
배치에 관련된 변경사항은 아래 두 파일만 보시면 됩니다.
- [socketEventTypes.ts](https://github.com/boostcampwm-2024/web10-QuizGround/pull/337/files#diff-b4924bb029e76b8eccc96e5a975d4c4ae39ea0c05e8da0196b00f308f5a7163e)
- [socketListener.ts](https://github.com/boostcampwm-2024/web10-QuizGround/pull/337/files#diff-c44bc366ca66852e3066134dc17ac4becb2dfa3c94e21a28164b7f4e1f2c9c84)
<br/>
=> [FE] updatePosition 및 chatMessage 이벤트 배치 적용 및 디자인 변경
